version: "3.9"

services:

  minio:
    image: minio/minio
    container_name: public-minio
    restart: always
    command: server
    volumes:
      - public-minio:/data
    environment:
      MINIO_VOLUMES: "/data"
      MINIO_SERVER_URL: "https://minio.${BASE_DOMAIN}"
    env_file:
      - .minio.env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.${BASE_DOMAIN}`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

networks:
  traefik:
    external: true

volumes:
  public-minio:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.126,nolock,soft,rw
      device: ":/mnt/user/Misc/public-minio"
