version: "3.9"

services:

  minio:
    image: minio/minio
    container_name: public-minio
    restart: always
    command: server --console-address ":9001"
    volumes:
      - public-minio:/data
    environment:
      MINIO_VOLUMES: "/data"
      MINIO_DOMAIN: "minio.${BASE_DOMAIN}"
      MINIO_SERVER_URL: "https://minio.${BASE_DOMAIN}"
      MINIO_BROWSER_REDIRECT_URL: "https://console.minio.${BASE_DOMAIN}"
    env_file:
      - .minio.env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      # Minio API
      - "traefik.http.routers.minio-api.rule=Host(`minio.${BASE_DOMAIN}`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls.certresolver=cloudflare"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"

      # Minio Console
      - "traefik.http.routers.minio-console.rule=Host(`console.minio.${BASE_DOMAIN}`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

networks:
  traefik:
    external: true

volumes:
  public-minio:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.126,nolock,soft,rw
      device: ":/mnt/user/Misc/public-minio"
